#pragma once

#include "kano/backlog_core/models/models.hpp"
#include <string>
#include <vector>
#include <optional>
#include <filesystem>
#include <cstdint>

namespace kano::backlog_ops {

/**
 * TopicOps manages "topic-scoped" work context.
 * Native topic context operations.
 *
 * Topic directory structure (under _kano/backlog/topics/<name>/):
 *   manifest.json    — metadata (created, agent, seed_items, pinned_docs)
 *   brief.md        — stable human-written brief (never auto-overwritten)
 *   brief.generated.md — deterministic distilled brief (auto-generated by distill)
 *   materials/      — collected raw context (clips/, links/, extracts/, logs/)
 *     clips/
 *     links/
 *     extracts/
 *     logs/
 *   synthesis/     — intermediate distillation outputs
 *   publish/       — prepared write-backs / patch skeletons
 */
class TopicOps {
public:
    // -------------------------------------------------------------------------
    // Result types
    // -------------------------------------------------------------------------

    struct TopicManifest {
        struct SnippetRef {
            std::string type = "snippet";
            std::string repo = "local";
            std::optional<std::string> revision;
            std::string file;
            std::vector<int> lines;
            std::string hash;
            std::optional<std::string> cached_text;
            std::optional<std::string> collected_at;
            std::optional<std::string> collector;
        };

        std::string topic;
        std::string agent;
        std::string created_at;     // ISO 8601
        std::string updated_at;      // ISO 8601
        std::string status;          // "open" | "closed"
        std::optional<std::string> closed_at;
        std::vector<std::string> seed_items;
        std::vector<std::string> pinned_docs;
        std::vector<SnippetRef> snippet_refs;
        std::vector<std::string> related_topics;
        bool has_spec = false;
    };

    struct TopicStatus {
        std::string id;
        std::string title;
        std::string status;
        bool is_active;
        int item_count;
        int pinned_doc_count;
        std::string created_at;
        std::string updated_at;
    };

    struct CreateResult {
        std::string topic;
        std::filesystem::path topic_path;
        std::string agent;
        std::string created_at;
    };

    struct AddItemResult {
        std::string topic;
        std::string item_ref;
        bool added;       // true if new, false if already present
    };

    struct SwitchResult {
        std::string topic;
        int item_count;
        int pinned_doc_count;
    };

    // -------------------------------------------------------------------------
    // Context export
    // -------------------------------------------------------------------------

    /** Single item summary in a context bundle. */
    struct ItemSummary {
        std::string uid;
        std::string id;
        std::string title;
        std::string type;
        std::string state;
        std::string priority;
        std::string path;
        bool error = false;
        std::string error_msg;
    };

    /** Single pinned document entry in a context bundle. */
    struct PinnedDocEntry {
        std::string path;
        std::string content;
        bool error = false;
        std::string error_msg;
    };

    /** Complete context bundle returned by export_context. */
    struct TopicContextBundle {
        std::string topic;
        std::vector<ItemSummary> items;
        std::vector<PinnedDocEntry> pinned_docs;
        std::string generated_at;  // ISO 8601
    };

    struct TopicAuditOptions {
        int ttl_days = 14;
        int stale_days = 30;
        std::optional<std::string> as_of;
    };

    struct TopicAuditEntry {
        std::string topic;
        std::string path;
        std::string status;
        std::string created_at;
        std::string updated_at;
        std::string closed_at;
        int age_days = -1;
        int inactive_days = -1;
        std::vector<std::string> active_agents;
        int item_count = 0;
        int open_item_count = 0;
        int done_item_count = 0;
        int dropped_item_count = 0;
        int pinned_doc_count = 0;
        bool materials_present = false;
        std::uintmax_t materials_size_bytes = 0;
        int snapshot_count = 0;
        bool has_date_prefix = false;
        std::string date_prefix;
        std::vector<std::string> stale_reasons;
        std::string recommendation;
    };

    struct TopicAuditReport {
        std::string as_of;
        int ttl_days = 14;
        int stale_days = 30;
        bool mutated = false;
        std::vector<TopicAuditEntry> topics;
    };

    /**
     * Export topic context as a structured bundle.
     * Does NOT write a file — returns the bundle for CLI formatting.
     *
     * Resolves each seed item to its path and extracts frontmatter metadata.
     * Loads the content of each pinned document.
     *
     * Throws std::runtime_error if the topic does not exist.
     */
    static TopicContextBundle export_context(
        const std::string& topic_name,
        const std::filesystem::path& backlog_root
    );

    static TopicAuditReport audit_topics(
        const std::filesystem::path& backlog_root,
        const TopicAuditOptions& options = {}
    );

    static std::string render_audit_report(
        const TopicAuditReport& report,
        const std::string& format
    );

    // -------------------------------------------------------------------------
    // Topic lifecycle
    // -------------------------------------------------------------------------

    /**
     * Create a new topic directory with manifest.json.
     * Throws TopicError if topic already exists.
     */
    static CreateResult create_topic(
        const std::string& name,
        const std::string& agent,
        const std::filesystem::path& backlog_root
    );

    static bool has_date_prefix(const std::string& topic_name);

    static void validate_topic_name(const std::string& topic_name);

    /**
     * Add a backlog item (by ID, UID, or path) to a topic's seed_items.
     * Throws TopicError if topic does not exist.
     */
    static AddItemResult add_item(
        const std::string& topic_name,
        const std::string& item_ref,
        const std::filesystem::path& backlog_root
    );

    /**
     * List all topics under backlog_root/topics/.
     * Returns metadata for each topic.
     */
    static std::vector<TopicStatus> list_topics(
        const std::filesystem::path& backlog_root,
        const std::optional<std::string>& active_agent = std::nullopt
    );

    /**
     * Switch to a topic (sets it as active for the given agent).
     * Throws TopicError if topic does not exist.
     */
    static SwitchResult switch_topic(
        const std::string& topic_name,
        const std::string& agent,
        const std::filesystem::path& backlog_root
    );

    /**
     * Distill materials into brief.generated.md.
     * Reads items and pinned docs, generates deterministic brief.
     * Returns path to generated brief file.
     */
    static std::filesystem::path distill(
        const std::string& topic_name,
        const std::filesystem::path& backlog_root
    );

    /**
     * Get the currently active topic ID for an agent.
     */
    static std::optional<std::string> get_current_topic(
        const std::string& agent,
        const std::filesystem::path& backlog_root
    );

    /**
     * Get status of a specific topic.
     */
    static TopicStatus get_topic_status(
        const std::string& topic_name,
        const std::filesystem::path& backlog_root
    );

    // -------------------------------------------------------------------------
    // Internal helpers
    // -------------------------------------------------------------------------

    /** Compute path to topic directory. */
    static std::filesystem::path get_topic_path(
        const std::string& topic_name,
        const std::filesystem::path& backlog_root
    );

    /** Load manifest.json for a topic. Returns nullopt on failure. */
    static std::optional<TopicManifest> load_manifest(
        const std::filesystem::path& topic_path
    );

    /** Save manifest.json for a topic. */
    static void save_manifest(
        const std::filesystem::path& topic_path,
        const TopicManifest& manifest
    );
};

} // namespace kano::backlog_ops
