#pragma once

#include "kano/backlog_core/models/models.hpp"
#include <string>
#include <vector>
#include <optional>
#include <filesystem>

namespace kano::backlog_ops {

/**
 * TopicOps manages "topic-scoped" work context.
 * Ported from topic.py
 *
 * Topic directory structure (under _kano/backlog/topics/<name>/):
 *   manifest.json    — metadata (created, agent, seed_items, pinned_docs)
 *   brief.md        — stable human-written brief (never auto-overwritten)
 *   brief.generated.md — deterministic distilled brief (auto-generated by distill)
 *   materials/      — collected raw context (clips/, links/, extracts/, logs/)
 *     clips/
 *     links/
 *     extracts/
 *     logs/
 *   synthesis/     — intermediate distillation outputs
 *   publish/       — prepared write-backs / patch skeletons
 */
class TopicOps {
public:
    // -------------------------------------------------------------------------
    // Result types
    // -------------------------------------------------------------------------

    struct TopicManifest {
        std::string topic;
        std::string agent;
        std::string created_at;     // ISO 8601
        std::string updated_at;      // ISO 8601
        std::string status;          // "open" | "closed"
        std::vector<std::string> seed_items;
        std::vector<std::string> pinned_docs;
    };

    struct TopicStatus {
        std::string id;
        std::string title;
        std::string status;
        bool is_active;
        int item_count;
        int pinned_doc_count;
        std::string created_at;
        std::string updated_at;
    };

    struct CreateResult {
        std::string topic;
        std::filesystem::path topic_path;
        std::string agent;
        std::string created_at;
    };

    struct AddItemResult {
        std::string topic;
        std::string item_ref;
        bool added;       // true if new, false if already present
    };

    struct SwitchResult {
        std::string topic;
        int item_count;
        int pinned_doc_count;
    };

    // -------------------------------------------------------------------------
    // Context export
    // -------------------------------------------------------------------------

    /** Single item summary in a context bundle. */
    struct ItemSummary {
        std::string uid;
        std::string id;
        std::string title;
        std::string type;
        std::string state;
        std::string priority;
        std::string path;
        bool error = false;
        std::string error_msg;
    };

    /** Single pinned document entry in a context bundle. */
    struct PinnedDocEntry {
        std::string path;
        std::string content;
        bool error = false;
        std::string error_msg;
    };

    /** Complete context bundle returned by export_context. */
    struct TopicContextBundle {
        std::string topic;
        std::vector<ItemSummary> items;
        std::vector<PinnedDocEntry> pinned_docs;
        std::string generated_at;  // ISO 8601
    };

    /**
     * Export topic context as a structured bundle.
     * Does NOT write a file — returns the bundle for CLI formatting.
     *
     * Resolves each seed item to its path and extracts frontmatter metadata.
     * Loads the content of each pinned document.
     *
     * Throws std::runtime_error if the topic does not exist.
     */
    static TopicContextBundle export_context(
        const std::string& topic_name,
        const std::filesystem::path& backlog_root
    );

    // -------------------------------------------------------------------------
    // Topic lifecycle
    // -------------------------------------------------------------------------

    /**
     * Create a new topic directory with manifest.json.
     * Throws TopicError if topic already exists.
     */
    static CreateResult create_topic(
        const std::string& name,
        const std::string& agent,
        const std::filesystem::path& backlog_root
    );

    /**
     * Add a backlog item (by ID, UID, or path) to a topic's seed_items.
     * Throws TopicError if topic does not exist.
     */
    static AddItemResult add_item(
        const std::string& topic_name,
        const std::string& item_ref,
        const std::filesystem::path& backlog_root
    );

    /**
     * List all topics under backlog_root/topics/.
     * Returns metadata for each topic.
     */
    static std::vector<TopicStatus> list_topics(
        const std::filesystem::path& backlog_root,
        const std::optional<std::string>& active_agent = std::nullopt
    );

    /**
     * Switch to a topic (sets it as active for the given agent).
     * Throws TopicError if topic does not exist.
     */
    static SwitchResult switch_topic(
        const std::string& topic_name,
        const std::string& agent,
        const std::filesystem::path& backlog_root
    );

    /**
     * Distill materials into brief.generated.md.
     * Reads items and pinned docs, generates deterministic brief.
     * Returns path to generated brief file.
     */
    static std::filesystem::path distill(
        const std::string& topic_name,
        const std::filesystem::path& backlog_root
    );

    /**
     * Get the currently active topic ID for an agent.
     */
    static std::optional<std::string> get_current_topic(
        const std::string& agent,
        const std::filesystem::path& backlog_root
    );

    /**
     * Get status of a specific topic.
     */
    static TopicStatus get_topic_status(
        const std::string& topic_name,
        const std::filesystem::path& backlog_root
    );

    // -------------------------------------------------------------------------
    // Internal helpers
    // -------------------------------------------------------------------------

    /** Compute path to topic directory. */
    static std::filesystem::path get_topic_path(
        const std::string& topic_name,
        const std::filesystem::path& backlog_root
    );

    /** Load manifest.json for a topic. Returns nullopt on failure. */
    static std::optional<TopicManifest> load_manifest(
        const std::filesystem::path& topic_path
    );

    /** Save manifest.json for a topic. */
    static void save_manifest(
        const std::filesystem::path& topic_path,
        const TopicManifest& manifest
    );
};

} // namespace kano::backlog_ops
